<a href="https://colab.research.google.com/github/WalidYaser/Deep-Learning/blob/main/Transformer_model_is_trained_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# -----------------------------
# 1. Input sentence and tokenization
# -----------------------------
sentence = "What are the symptoms of diabetes?"
tokens = sentence.replace("?", " ?").split()
print("Tokens:", tokens)

# -----------------------------
# 2. Hyperparameters
# -----------------------------
np.random.seed(42)
d_model = 8   # embedding dimension
d_k = 8       # dimension of query/key
n_tokens = len(tokens)

# -----------------------------
# 3. Create toy token embeddings
#    (In a real Transformer, these are learned embeddings)
# -----------------------------
token_embeddings = np.random.randn(n_tokens, d_model)

# -----------------------------
# 4. Positional encoding
# -----------------------------
def positional_encoding(seq_len, d_model):
    PE = np.zeros((seq_len, d_model))
    positions = np.arange(seq_len)[:, np.newaxis]
    div_term = np.exp(np.arange(0, d_model, 2) * (-np.log(10000.0) / d_model))

    PE[:, 0::2] = np.sin(positions * div_term)
    PE[:, 1::2] = np.cos(positions * div_term)
    return PE

pos_encoding = positional_encoding(n_tokens, d_model)

# Final encoder input
X = token_embeddings + pos_encoding

# -----------------------------
# 5. Initialize weight matrices
# -----------------------------
W_Q = np.random.randn(d_model, d_k)
W_K = np.random.randn(d_model, d_k)
W_V = np.random.randn(d_model, d_k)

# -----------------------------
# 6. Compute Q, K, V
# -----------------------------
Q = X @ W_Q
K = X @ W_K
V = X @ W_V

# -----------------------------
# 7. Compute scaled dot-product attention scores
# -----------------------------
scores = (Q @ K.T) / np.sqrt(d_k)

# -----------------------------
# 8. Softmax function
# -----------------------------
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

attention_weights = softmax(scores)

# -----------------------------
# 9. Compute self-attention output
# -----------------------------
attention_output = attention_weights @ V

# -----------------------------
# 10. Print results
# -----------------------------
np.set_printoptions(precision=3, suppress=True)

print("\nSelf-Attention Score Matrix:")
print(scores)

print("\nAttention Weight Matrix (after softmax):")
print(attention_weights)

print("\nSelf-Attention Output:")
print(attention_output)


Tokens: ['What', 'are', 'the', 'symptoms', 'of', 'diabetes', '?']

Self-Attention Score Matrix:
[[-3.682  0.14   1.151 26.967 14.748 13.948 12.428]
 [ 4.333 -2.817  1.898 11.637 -5.161  5.201  4.354]
 [-7.459  1.778 -2.948 -5.988  4.155 -1.079 -4.022]
 [ 1.141 -8.133  4.214 10.205 -5.923  2.008  7.296]
 [ 4.091  0.294 -2.268  6.572 -3.915  1.291 -4.526]
 [10.113 -2.624  3.19  20.981 -4.107  8.867  8.991]
 [-1.639  3.024 -2.796 15.017  9.278  8.43   2.209]]

Attention Weight Matrix (after softmax):
[[0.    0.    0.    1.    0.    0.    0.   ]
 [0.001 0.    0.    0.997 0.    0.002 0.001]
 [0.    0.084 0.001 0.    0.91  0.005 0.   ]
 [0.    0.    0.002 0.946 0.    0.    0.052]
 [0.077 0.002 0.    0.917 0.    0.005 0.   ]
 [0.    0.    0.    1.    0.    0.    0.   ]
 [0.    0.    0.    0.995 0.003 0.001 0.   ]]

Self-Attention Output:
[[-1.899  6.424 -0.03   1.581 -0.471  2.626 -2.598 -0.07 ]
 [-1.895  6.418 -0.02   1.584 -0.487  2.623 -2.598 -0.066]
 [-0.597  0.739 -2.04   1.528  2.78  -2